### ISSUE TITLE
DialogAndroid.show() One More Param Needed - Package Broken

### ISSUE THREAD

**Issue by thomashzhang** [florianstahr/react-native-settings-components#15]
Looks like the package is broken, possibly because of breaking dependency changes. I am getting this error when I click on the setting itself:

```
TypeError: null is not an object (evaluating '_reactNative.NativeModules.DialogAndroid.show')]
at node_modules/react-native-settings-components/src/edit-text/edit-text.jsx:220:6 in SettingsEditText#render
at node_modules/react-native-settings-components/src/edit-text/edit-text.jsx:202:48 in SettingsEditText#render
```

<img width="325" alt="Screen Shot 2022-01-08 at 5 30 58 PM" src="https://user-images.githubusercontent.com/2775684/148665727-2afe490a-7736-416b-a7db-0145c85c993f.png">

**Comment by jazbek** [comment]
~~@thomashzhang I am also running into this issue, did you find a solution?~~

Update, I fixed this issue -- `react-native-dialogs` library needed to be manually linked:
https://github.com/react-native-dialogs/react-native-dialogs#manual-linking

Furthermore, in step 1, the word `compile` needs to be changed to `implementation`. Followed the rest of the steps, and all is working. Using react-native 0.68.2 and react 17.0.2.
